import AppKit
import Foundation

public protocol ClipboardWatcherDelegate: AnyObject {
    func clipboardDidChange(newText: String, hash: String)
}

public final class ClipboardWatcher {
    public static let shared = ClipboardWatcher()
    
    public weak var delegate: ClipboardWatcherDelegate?
    
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int = 0
    private var timer: Timer?
    
    // Ring buffer of known hashes (both sent and received) to prevent echo loops
    private var knownHashes: Set<String> = []
    private var hashHistory: [String] = []
    private let maxHistorySize = 100
    private let lock = NSLock()
    
    // Filter out password manager copy types
    private let concealedPasteboardTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.blink_mind.concealed")
    ]
    
    public var ignorePasswords: Bool = true
    
    private init() {
        self.lastChangeCount = pasteboard.changeCount
    }
    
    public func startListening() {
        stopListening()
        self.lastChangeCount = pasteboard.changeCount
        
        // Lightweight polling: 250ms interval with zero-allocation changeCount check
        self.timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            self?.checkForChanges()
        }
        RunLoop.main.add(self.timer!, forMode: .common)
    }
    
    public func stopListening() {
        timer?.invalidate()
        timer = nil
    }
    
    public func markHashAsHandled(_ hash: String) {
        lock.lock()
        defer { lock.unlock() }
        
        knownHashes.insert(hash)
        hashHistory.append(hash)
        if hashHistory.count > maxHistorySize {
            let removed = hashHistory.removeFirst()
            knownHashes.remove(removed)
        }
    }
    
    public func isHashKnown(_ hash: String) -> Bool {
        lock.lock()
        defer { lock.unlock() }
        return knownHashes.contains(hash)
    }
    
    public func writeToPasteboard(text: String, hash: String) {
        markHashAsHandled(hash)
        
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            self.pasteboard.clearContents()
            self.pasteboard.setString(text, forType: .string)
            self.lastChangeCount = self.pasteboard.changeCount
        }
    }
    
    private func checkForChanges() {
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount
        
        // Check if item is marked as concealed / password
        if ignorePasswords {
            if let types = pasteboard.types {
                for concealed in concealedPasteboardTypes {
                    if types.contains(concealed) {
                        return // Skip syncing passwords
                    }
                }
            }
        }
        
        // Read text content
        guard let copiedString = pasteboard.string(forType: .string), !copiedString.isEmpty else {
            return
        }
        
        let hash = CryptoEngine.shared.computeSHA256(string: copiedString)
        if isHashKnown(hash) {
            // Already synced or just received from remote
            return
        }
        
        markHashAsHandled(hash)
        delegate?.clipboardDidChange(newText: copiedString, hash: hash)
    }
}
